### ISSUE TITLE
Enable Deppy to be imported by other packages

### ISSUE THREAD

**Issue by oceanc80** [operator-framework/deppy#73]
Move all interfaces and broader implementations of those interfaces from `internal` to `pkg` 
Only keep internal implementation details of the interfaces in `internal`

**Make Deppy importable**
- [ ] Keep [solver](https://github.com/operator-framework/deppy/tree/main/internal/solver) package in `internal`
- [ ] Export [sat/constraints.go](https://github.com/operator-framework/deppy/blob/main/internal/sat/constraints.go) and [sat/variable.go](https://github.com/operator-framework/deppy/blob/main/internal/sat/variable.go)

**Comment by akihikokuroda** [comment]
How is the solver triggered by keeping the `solver` package in `internal`?  I think the 'sat' package should be `internal` but the `solver` package may need to be exported.

**Comment by perdasilva** [comment]
Yeah, I agree. It might be hard to keep the sat package internal though. The reason is the constraint interface relies has package internal methods that are required by the solver. Furthermore, those methods make use of package internal structures (e.g. litMapping). For now, I think we should move everything to pkg to make it easy to be imported by other package. Then move things that are internal to the implementation to `internal`. This may require some refactoring of the sat solver package though.

**Comment by perdasilva** [comment]
I've put up the PR to move everything to `pkg`: https://github.com/operator-framework/deppy/pull/79

**Comment by akihikokuroda** [comment]
It may be difficult to achieve #50 once we expose the sat package. Are we giving it up?
